# Generated by Django 4.2 on 2023-04-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PFApp', '0004_comment_parent_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'ordering': ['end_date'],
            },
        ),
    ]
