# Generated by Django 4.2 on 2023-04-12 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PFApp', '0008_remove_comment_parent_comment_comment_updated_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='content',
        ),
    ]
