# Generated by Django 4.2 on 2023-04-12 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PFApp', '0010_rename_content_comment_comment_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_content',
            new_name='content',
        ),
    ]
